name: StigglesLearn
version: '${project.version}'
main: com.stigglespatch.main.Main
api-version: 1.19
authors: [ Accnt ]
commands:
  dungeon:
    description: For admins.
  smp:
    description: For admins only.
  creative:
    description: For admins- only.

